services:
  server:
    image: golang:1.23
    restart: unless-stopped
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: go run main.go

  redis:
    image: redis:7
    ports:
      - 6379:6379
    restart: unless-stopped

  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: watermill
      POSTGRES_DB: watermill
      POSTGRES_PASSWORD: "password"
