service:
  prepare:
    - go run dev/consolidate-gomods/main.go >> go.mod
    - GO111MODULE=on go mod vendor
    - rm vendor/github.com/ThreeDotsLabs/watermill/ -rf
    - rm -rf docs/ # todo - reenable

run:
  concurrency: 8
