ignore:
  - "pubsub/tests" # test helpers used to test Pub/Subs

comment: no # do not comment PR with the result

coverage:
  precision: 0
  status:
    patch: false # do not run coverage on patch nor changes
    project:
      default:
        target: auto
        threshold: 5%
