services:
  server:
    image: golang:1.23
    restart: unless-stopped
    depends_on:
      - nats
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: go run main.go

  nats:
    image: nats:2
    ports:
      - "0.0.0.0:4222:4222"
    restart: unless-stopped
    command: ["-js"]
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
