version: '3'
services:
  server:
    image: golang:1.18
    restart: unless-stopped
    depends_on:
      - nats-jetstream
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: go run main.go

  nats-jetstream:
    image: nats:2.7.4
    restart: unless-stopped
    command: -js
    ports:
      - "4222:4222"
