CREATE TABLE IF NOT EXISTS events (
  idx BIGINT AUTO_INCREMENT,
  uuid BINARY(16) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  payload JSON NOT NULL,
  metadata JSON NOT NULL,
  topic VARCHAR(255) NOT NULL,
  PRIMARY KEY (idx),
  UNIQUE(uuid)
);

