version: '3'
services:
  server:
    image: golang:1.11
    restart: on-failure
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go

  rabbitmq:
    image: rabbitmq:3.7
    restart: on-failure
