version: '3'
services:
  server:
    image: golang:1.17
    restart: unless-stopped
    depends_on:
      - mysql
      - postgres
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: go run .

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: watermill
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  postgres:
    image: postgres:11
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: watermill
      POSTGRES_DB: watermill
      POSTGRES_PASSWORD: "password"
