{
 "title": "Watermill",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "15s, 30s, 1m,10m,30m,1h,6h,12h,1d"
   },
   { "name": "node", "query": "label_values(instance)" },
   {
    "name": "handler",
    "label": "handler",
    "query": "label_values(handler_execution_time_seconds_count{instance=~\"$node\"}, handler_name)"
   }
  ]
 },
 "panels": [
  { "title": "Current stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages received",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(subscriber_messages_received_total{instance=~\"$node\", handler_name=~\"$handler\"})"
    }
   ]
  },
  {
   "title": "Handler errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(handler_execution_time_seconds_count{instance=~\"$node\", handler_name=~\"$handler\", success=\"false\"})"
    }
   ]
  },
  {
   "title": "Messages published",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(publish_time_seconds_count{instance=~\"$node\", handler_name=~\"$handler\", success=\"true\"})"
    }
   ]
  },
  {
   "title": "Publisher errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(publish_time_seconds_count{instance=~\"$node\", handler_name=~\"$handler\", success=\"false\"})"
    }
   ]
  },
  {
   "title": "Subscriber count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(subscriber_messages_received_total{acked=\"acked\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Handler count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(handler_execution_time_seconds_count{success=\"true\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Publisher count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(publish_time_seconds_count{success=\"true\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Made with ❤ by",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "content": "<center><a href=\"https://threedots.tech/\"><img height=\"100px\" width=\"auto\" src=\"https://d33wubrfki0l68.cloudfront.net/b2caa196e83a45551ec03746000c2ca1543651b9/19f78/img/logo.png\" /></a></center>"
  },
  { "title": "Handler & publisher operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Handler op/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(handler_execution_time_seconds_count{instance=~\"$node\", handler_name=~\"$handler\"}[$interval])) by (handler_name, instance)",
     "legendFormat": "{{handler_name}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Publish op/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(publish_time_seconds_count{instance=~\"$node\", handler_name=~\"$handler\"}[$interval])) by (handler_name, instance)",
     "legendFormat": "{{handler_name}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Handler failed op/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(handler_execution_time_seconds_count{instance=~\"$node\", handler_name=~\"$handler\", success=\"false\"}[$interval])) by (handler_name, instance)",
     "legendFormat": "{{handler_name}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Publish failed op/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(publish_time_seconds_count{instance=~\"$node\", handler_name=~\"$handler\", success=\"false\"}[$interval])) by (handler_name, instance)",
     "legendFormat": "{{handler_name}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Handler duration @ $node nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(handler_execution_time_seconds_bucket{instance=~\"$node\", handler_name=~\"$handler\"}[$interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(handler_execution_time_seconds_bucket{instance=~\"$node\", handler_name=~\"$handler\"}[$interval])) by ( le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(handler_execution_time_seconds_bucket{instance=~\"$node\", handler_name=~\"$handler\"}[$interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Publish duration @ $node nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(publish_time_seconds_bucket{instance=~\"$node\", handler_name=~\"$handler\"}[$interval])) by (handler_name, le, publisher_name))",
     "legendFormat": "p99 {{handler_name}}→{{publisher_name}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(publish_time_seconds_bucket{instance=~\"$node\", handler_name=~\"$handler\"}[$interval])) by (handler_name, le, publisher_name))",
     "legendFormat": "p90 {{handler_name}}→{{publisher_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(publish_time_seconds_bucket{instance=~\"$node\", handler_name=~\"$handler\"}[$interval])) by (handler_name, le, publisher_name))",
     "legendFormat": "p50 {{handler_name}}→{{publisher_name}}"
    }
   ]
  }
 ]
}