version: '3'
services:
  server:
    image: golang:1.11
    restart: unless-stopped
    depends_on:
      - nats-streaming
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: go run main.go

  nats-streaming:
    image: nats-streaming:0.11.2
    restart: unless-stopped
