version: '3'
services:
  server:
    image: golang:1.11
    restart: unless-stopped
    depends_on:
      - googlecloud
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    environment:
      # use local emulator instead of google cloud engine
      PUBSUB_EMULATOR_HOST: "googlecloud:8085"
    working_dir: /app
    command: go run main.go

  googlecloud:
    image: google/cloud-sdk:228.0.0
    entrypoint: gcloud --quiet beta emulators pubsub start --host-port=googlecloud:8085 --verbosity=debug --log-http
    restart: unless-stopped
