version: '3'
services:
  server:
    image: golang:1.15
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: 'go run .'

  worker:
    image: golang:1.15
    restart: unless-stopped
    volumes:
      - ./worker:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: 'go run .'

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: example
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
