package cqrs

// CommandTopicGenerator generates topic name for CommandBus and CommandProcessor
// commandName is based on command name generated by Marshaler.Name method.
type CommandTopicGenerator func(commandName string) string
