package cqrs

// EventTopicGenerator generates topic name for EventBus and EventProcessor
// eventName is based on event name generated by Marshaler.Name method.
type EventTopicGenerator func(eventName string) string
