// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testdata/events.proto

package cqrs_test

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestProtobufEvent struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	When                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=when,proto3" json:"when,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TestProtobufEvent) Reset()         { *m = TestProtobufEvent{} }
func (m *TestProtobufEvent) String() string { return proto.CompactTextString(m) }
func (*TestProtobufEvent) ProtoMessage()    {}
func (*TestProtobufEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_37faf0ac8d97ee4c, []int{0}
}

func (m *TestProtobufEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestProtobufEvent.Unmarshal(m, b)
}
func (m *TestProtobufEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestProtobufEvent.Marshal(b, m, deterministic)
}
func (m *TestProtobufEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestProtobufEvent.Merge(m, src)
}
func (m *TestProtobufEvent) XXX_Size() int {
	return xxx_messageInfo_TestProtobufEvent.Size(m)
}
func (m *TestProtobufEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TestProtobufEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TestProtobufEvent proto.InternalMessageInfo

func (m *TestProtobufEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TestProtobufEvent) GetWhen() *timestamp.Timestamp {
	if m != nil {
		return m.When
	}
	return nil
}

func init() {
	proto.RegisterType((*TestProtobufEvent)(nil), "cqrs_test.TestProtobufEvent")
}

func init() { proto.RegisterFile("testdata/events.proto", fileDescriptor_37faf0ac8d97ee4c) }

var fileDescriptor_37faf0ac8d97ee4c = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x49, 0x2d, 0x2e,
	0x49, 0x49, 0x2c, 0x49, 0xd4, 0x4f, 0x2d, 0x4b, 0xcd, 0x2b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x4c, 0x2e, 0x2c, 0x2a, 0x8e, 0x07, 0xc9, 0x49, 0xc9, 0xa7, 0xe7, 0xe7, 0xa7,
	0xe7, 0xa4, 0xea, 0x83, 0x25, 0x92, 0x4a, 0xd3, 0xf4, 0x4b, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12,
	0x73, 0x0b, 0x20, 0x6a, 0x95, 0x82, 0xb9, 0x04, 0x43, 0x52, 0x8b, 0x4b, 0x02, 0xa0, 0xf2, 0xae,
	0x20, 0x73, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98,
	0x32, 0x53, 0x84, 0xf4, 0xb8, 0x58, 0xca, 0x33, 0x52, 0xf3, 0x24, 0x98, 0x15, 0x18, 0x35, 0xb8,
	0x8d, 0xa4, 0xf4, 0x20, 0x86, 0xea, 0xc1, 0x0c, 0xd5, 0x0b, 0x81, 0x19, 0x1a, 0x04, 0x56, 0x97,
	0xc4, 0x06, 0x96, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xff, 0x4e, 0x39, 0x0e, 0xa0, 0x00,
	0x00, 0x00,
}
