name: pr-examples
on:
  pull_request:
    paths:
      - '_examples/**/*'

jobs:
  validate-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.21.1'
      - run: make validate_examples
        timeout-minutes: 30