name: pr
on:
  pull_request:
jobs:
  ci:
    uses: ThreeDotsLabs/watermill/.github/workflows/tests.yml@bump-deps-052026
    with:
      codecov: true
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
