name: pr
on:
  pull_request:
jobs:
  ci:
    uses: ThreeDotsLabs/watermill/.github/workflows/tests.yml@assert-messages
    with:
      codecov: true
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
